version: '3.8'
services:
  backend:
    build: ./backend
    container_name: backend
    restart: always
    environment:
      - APP_NAME=FlaskApp
    volumes:
      - './backend:/backend'
    expose:
      - 8080
  nginx:
      build: ./nginx
      container_name: nginx
      restart: always
      ports:
          - "80:80"
  frontend:
    build: ./frontend
    container_name: frontend
    restart: always
    volumes:
      - './frontend:/frontend'
    ports:
      - "8000:8000"
      - "5000:5000"
